"""add ingest tokens, source profiles, import batches, staged transactions, merchant rules

Revision ID: a8225ffcfeb6
Revises: df8617febf74
Create Date: 2026-09-07 12:10:13.363384

Purely additive: five new tables, nothing touched on the existing four. Safe to
run against the live database.

Together these are the pipeline every feeder shares. `staged_transaction` is
the important one -- everything ingested lands there and nothing reaches the
real `transaction` table without being reviewed first. Its
UNIQUE (user_id, dedup_hash) is what makes ingest idempotent: re-running an
import, or a wallet notification arriving via both the safety-net POST and the
deep link, converges on one row instead of duplicating.

Generated against a scratch database built from this migration chain, never
against a real one -- see the baseline revision for why that matters here.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8225ffcfeb6'
down_revision = 'df8617febf74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingest_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('prefix', sa.String(length=8), nullable=False),
    sa.Column('scope', sa.String(length=30), server_default='ingest', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingest_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingest_token_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_ingest_token_user_id'), ['user_id'], unique=False)

    op.create_table('merchant_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pattern', sa.String(length=300), nullable=False),
    sa.Column('is_regex', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('txn_type', sa.String(length=10), nullable=True),
    sa.Column('hits', sa.Integer(), server_default='0', nullable=False),
    sa.Column('auto_learned', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'pattern', name='uq_merchant_rule_pattern')
    )
    with op.batch_alter_table('merchant_rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_merchant_rule_user_id'), ['user_id'], unique=False)

    op.create_table('source_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('company_id', sa.String(length=30), nullable=False),
    sa.Column('account_last4', sa.String(length=8), nullable=True),
    sa.Column('combine_installments', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('exclude_patterns', sa.JSON(), nullable=True),
    sa.Column('column_mapping', sa.JSON(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_profile_user_id'), ['user_id'], unique=False)

    op.create_table('import_batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('source_profile_id', sa.Integer(), nullable=True),
    sa.Column('window_start', sa.Date(), nullable=True),
    sa.Column('window_end', sa.Date(), nullable=True),
    sa.Column('received', sa.Integer(), server_default='0', nullable=False),
    sa.Column('new', sa.Integer(), server_default='0', nullable=False),
    sa.Column('matched', sa.Integer(), server_default='0', nullable=False),
    sa.Column('proposed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('ambiguous', sa.Integer(), server_default='0', nullable=False),
    sa.Column('suppressed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=10), server_default='running', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_profile_id'], ['source_profile.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_batch', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_batch_user_id'), ['user_id'], unique=False)

    op.create_table('staged_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('source_profile_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=True),
    sa.Column('dedup_hash', sa.String(length=64), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('txn_date', sa.Date(), nullable=True),
    sa.Column('posted_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('exchange_rate', sa.Float(), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=True),
    sa.Column('merchant_raw', sa.String(length=300), nullable=True),
    sa.Column('merchant_clean', sa.String(length=300), nullable=True),
    sa.Column('memo', sa.String(length=300), nullable=True),
    sa.Column('issuer_status', sa.String(length=30), nullable=True),
    sa.Column('installment_no', sa.Integer(), nullable=True),
    sa.Column('installment_total', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=15), server_default='new', nullable=False),
    sa.Column('matched_txn_id', sa.Integer(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('candidate_ids', sa.JSON(), nullable=True),
    sa.Column('suggested_category', sa.String(length=120), nullable=True),
    sa.Column('suggested_description', sa.String(length=300), nullable=True),
    sa.Column('category_confidence', sa.Float(), nullable=True),
    sa.Column('created_txn_id', sa.Integer(), nullable=True),
    sa.Column('ignored_reason', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batch.id'], ),
    sa.ForeignKeyConstraint(['created_txn_id'], ['transaction.id'], ),
    sa.ForeignKeyConstraint(['matched_txn_id'], ['transaction.id'], ),
    sa.ForeignKeyConstraint(['source_profile_id'], ['source_profile.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'dedup_hash', name='uq_staged_user_dedup')
    )
    with op.batch_alter_table('staged_transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staged_transaction_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_staged_transaction_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_staged_transaction_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staged_transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staged_transaction_user_id'))
        batch_op.drop_index(batch_op.f('ix_staged_transaction_state'))
        batch_op.drop_index(batch_op.f('ix_staged_transaction_batch_id'))

    op.drop_table('staged_transaction')
    with op.batch_alter_table('import_batch', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_batch_user_id'))

    op.drop_table('import_batch')
    with op.batch_alter_table('source_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_profile_user_id'))

    op.drop_table('source_profile')
    with op.batch_alter_table('merchant_rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_merchant_rule_user_id'))

    op.drop_table('merchant_rule')
    with op.batch_alter_table('ingest_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingest_token_user_id'))
        batch_op.drop_index(batch_op.f('ix_ingest_token_token_hash'))

    op.drop_table('ingest_token')
    # ### end Alembic commands ###
