"""add transaction.created_at and refresh_token table

Revision ID: df8617febf74
Revises: ad1348f23c91
Create Date: 2026-09-07 11:20:24.093453

Two additions, both safe to run against the live database.

`transaction.created_at` closes a live bug rather than adding a feature:
`GET /api/transactions` already orders by `Transaction.created_at`, a column
the model never declared, so that route raised on every call. Existing rows are
backfilled from `date` rather than from `now()` -- stamping every historical
row with the migration timestamp would be a worse lie than the transaction's
own date, and it would make the column useless as a tie-breaker.

`refresh_token` gives sessions rotation and revocation. A stateless JWT cannot
be withdrawn, so logout could not truly end a session and a leaked refresh
token stayed valid for its full lifetime.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df8617febf74'
down_revision = 'ad1348f23c91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('issued_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('rotated_to', sa.String(length=64), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_token_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_token_user_id'), ['user_id'], unique=False)

    # Added nullable, backfilled from `date`, then tightened -- rather than
    # added NOT NULL with a now() default, which would give every historical
    # row the same meaningless timestamp.
    op.add_column(
        'transaction',
        sa.Column('created_at', sa.DateTime(), nullable=True),
    )
    op.execute(
        'UPDATE "transaction" '
        'SET created_at = date::timestamp '
        'WHERE created_at IS NULL'
    )
    op.alter_column(
        'transaction', 'created_at',
        existing_type=sa.DateTime(),
        nullable=False,
        server_default=sa.text('now()'),
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('refresh_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_token_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_token_token_hash'))

    op.drop_table('refresh_token')
    # ### end Alembic commands ###
